name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    env:
      CATKIN_LINT: true
      ROS_REPO: main
      UPSTREAM_WORKSPACE: .rosinstall
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        pip install flake8
    - name: Lint
      run: |
        flake8 -v
